### ISSUE TITLE
Are the old Gerbers usable?

### ISSUE THREAD

**Issue by vk5ln** [bvenneker/Chat64#2]
Looks like I did a JLCPCB order too soon. I sent off the Chat64 SMD gerbers to JLCPCB last week, I've just had an email to say my order is on it's way to me. 

I now see that the files have been removed due to an issue? Will my PCBs be useless? I used the production Gerber files.

**Comment by SvenPook** [comment]
My old cartridge is still working, so that shouldn't be an issue.
Chances are that your cartridge might be incompatible with your Commodore 64's mainboard revision.

**Comment by vk5ln** [comment]
Thank you for the reply.

**Comment by bvenneker** [comment]
No, please wait a few days for the new design. We will upload them to
github when we have received the proto PCBs and tested them.

Best,
Bart

Op zo 25 feb. 2024 20:57 schreef vk5ln ***@***.***>:

**Comment by vk5ln** [comment]
Too late :-) already have blank Chat64 SMD PCBs on the way. Oh well, they can join my pile of unused boards :-D

**Comment by Crouze** [comment]
I understand the frustration of finding an error on your board design after going public with it, and having to re-design and re-test. However, a little bit more openness would be appreciated. I too already have PCB's on their way of the retracted THT design. Not a big investment, but still. The questions I now have are simple:

 - which C64 mainboard revisions were found to be incompatible with your PCB design? Which are known to work?
 - can the retracted PCB be modified (with cut traces and bodge wires) to the new design, at least in theory?
 
 Thanks.

**Comment by bvenneker** [comment]
There is no error in the 'old' design. It works good on many C64s. Especially the newer C64-C. You may run into issues on older models. Then again, I think we have tested successfully on every revision including some very early ones. 
It also works great on the Ultimate 64 model. But forget about the C64 sx :-)

We expect the prototype pcb's at the end of this week, we will publish the new design as soon as we have tested them.

**Comment by Crouze** [comment]
Good to hear. Then I will populate my PCB which should also arrive at the end of this week (I hope) and assume it will work on my '64. Thanks for your reply.

**Comment by Crouze** [comment]
Well, I am having problems nevertheless.

Received the THT PCB's yesterday (Rev 2.8 it says) and soldered one of them up. Soldering went good, no issues there (not a novice here). The only point might be that the resistor hole spacing is too narrow for regular 6mm resistors despite there being more than enough space on the board. But that is not the problem.

As part of my troubleshooting I re-flashed both the ESP32 and the EEPROM, no change.

All chips were tested OK with the Retro Chip Tester.

Tested the cartridge on both of my C64's: an original and unmodified 250425, and a SixtyClone 250466. Both show the same behaviour.

The cartridge is unusable to work with because it constantly resets whenever settings are typed in (WiFi settings, Server settings). If left alone after boot it will show the start screen well. The function keys work well. But after the first character is entered on a settings screen the board will reset exactly 5 seconds after that.

The ESP32 board has a constant RED led, and a blue LED between resets.

Another thing I see is that the LED next to the reset switch on the board does not light up under any circumstance. The LED itself is good (and correctly soldered).

Maybe the developers can shed some light on this? My suspicion lies with the ESP32 board, but since it is still not clear what the issues were for the developers to retract the Gerber files (hardware, or software issue?) it is hard to guess.

I will probably put this little project aside for the time being, it is costing me more frustration than hoped for. Maybe I'll try again if it is a little bit more mature.

**Comment by Crouze** [comment]
Adding to my previous post, going through the ESP32 sketch I noticed that the blue LED turns on when there is actually a WiFi connection. I did manage to enter my SSID and password after many attempts, but the screens still say "WiFi not connected" yet the LED turns on. Also on the settings screen the entries are repeated at the next viewing of the screen, so for instance the SSID (lets say it is "MyWiFi") then shows as "MyWifiMyWifi", or with some random characters. Letting me believe that the EEPROM is not properly read/written.

I have changed out the ESP32, no change. Last thing I will do is to change the AT28C64B EEPROM with a spare.

**Comment by vk5ln** [comment]
As a final comment on this. If the SMD board is being re-worked, can I suggest a move to slightly larger SMD resistors and capacitors to help those hand soldering the boards? 

0402 (1005 metric) components are a bit small to easily manipulate and hand solder. 0603 would be easy to accommodate on the PCB and would help hand soldering assemblers immensely.

**Comment by bvenneker** [comment]
Kicad project (including gerbers) are now available in github
