### ISSUE TITLE
Ultimate64 compatibility 

### ISSUE THREAD

**Issue by berrydejager** [bvenneker/Chat64#3]
Would it be possible to use the Ultimate64, and its WiFi-capabilities, for the chat application?

**Comment by SvenPook** [comment]
at the moment focus lies on the Chat64 cartridge and underlying software. Maybe at a later point collaboration with the Ultimate64 hardware might take place. 
That being said: this is an opensource project. The software could be rewritten to run as a PRG instead of a cartridge. Feel free to experiment with it.

**Comment by berrydejager** [comment]
In the meanwhile I got the x-mas-special of the Chat64, this also enable me more to understand the logic for future experimenting with the U64.
